version: '3.9'

services:
  etl-runner:
    build: .
    container_name: etl_runner
    depends_on:
      - mongo
    environment:
      - SQL_SERVER_USER=sa
      - SQL_SERVER_PASS=francia92
      - SQL_SERVER_HOST=DESKTOP-GOCIPJK
      - SQL_SERVER_DB=HotSale
      - MONGODB_DB=ETL_Mercado_Libre
      - MONGO_URI=mongodb://mongo:27017/
    volumes:
      - .:/app
    networks:
      - etl-network

  mongo:
    image: mongo:6.0
    container_name: mongodb_container
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - etl-network

volumes:
  mongodb_data:

networks:
  etl-network:
