CREATE DATABASE EtlMercadoLibre;

USE EtlMercadoLibre;

CREATE TABLE Brands (
	id INT IDENTITY PRIMARY KEY NOT NULL,
	name NVARCHAR(MAX),	
)

CREATE TABLE MainCategories (
	id INT IDENTITY PRIMARY KEY NOT NULL,
	name NVARCHAR(MAX),	
)

CREATE TABLE Products (
	id INT IDENTITY PRIMARY KEY NOT NULL,
	title NVARCHAR(MAX),
	condition NVARCHAR(MAX) NULL,
	brand_id INT FOREIGN KEY REFERENCES Brands(id),
)